name: autopush

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # This cron expression triggers the workflow every day at 2 AM UTC

jobs:
  create-pr:
    steps:
      - name: create pull request
        run: gh pr create -B production/stable -H testing/rolling --title 'Regularly scheduled push to production' --body 'This is a test'
        with: 
          pr-labels: |
            automated
            autopush
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
