name: autopush

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # This cron expression triggers the workflow every day at 2 AM UTC

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create Pull Request
        run: |
          base_branch="production/stable"
          branch_to_merge="testing/rolling"
          gh pr create -B $base_branch -H $branch_to_merge --title "Regularly scheduled push to production" --body "This PR is merging the testing/rolling branch to production/stable. Feel free to close this PR if it's not ready for release."
          pr_number=$(gh pr list --base $base_branch --state open --json number --limit 1 | jq -r .[0].number)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
